ALTER TABLE EVENT_SCHEDULES
ADD COLUMN IF NOT EXISTS audi_name VARCHAR(50) NOT NULL DEFAULT 'Audi 1';

UPDATE EVENT_SCHEDULES
SET audi_name = 'Audi 1'
WHERE audi_name IS NULL OR TRIM(audi_name) = '';
